config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'people', to: 'home#people'
  get 'mission', to: 'home#mission'
  get 'imprint', to: 'home#imprint'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'net/http'

  def index
    uri = URI('https://ecosystem.iota.org/search_with_tags.json?tags=iota4earth&object_type=project')
    res = Net::HTTP.get(uri)
    if valid_json?(res)
      @projects = JSON.parse(res)
    else
      @people = []
    end
  end

  def people
    uri = URI('https://ecosystem.iota.org/search_with_tags.json?tags=iota4earth&object_type=user')
    res = Net::HTTP.get(uri)
    if valid_json?(res)
      @people = JSON.parse(res)
    else
      @people = []
    end
  end

  def mission

  end

  def imprint

  end

  private

  def valid_json?(string)
    begin
      !!JSON.parse(string)
    rescue JSON::ParserError
      false
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/home/imprint.html.erb
<div class="section">
  <div class="container">
      <h1>Legal Disclosure</h1>
      <h5>Information in accordance with Section 5 TMG</h5>
      <br>
      <p>Sebastian Heußer<br>
      Collingstraße 104<br>
      66424 Homburg</p>
      <br>
      <h2>Contact Information</h2>
      E-Mail: <a href="mailto:hello@iota4earth.org">hello@iota4earth.org</a><br>Internet address: <a href="www.iota4earth.org" target="_blank">www.iota4earth.org</a><br>
      <br>
      <h2>Graphics and Image Sources</h2>
      <a href="https://ecosystem.iota.org" target="_blank">https://ecosystem.iota.org</a>
      <br><br>
      <h2>Disclaimer</h2>
      Accountability for content<br>
      The contents of our pages have been created with the utmost care. However, we cannot guarantee the contents'
      accuracy, completeness or topicality. According to statutory provisions, we are furthermore responsible for
      our own content on these web pages. In this matter, please note that we are not obliged to monitor
      the transmitted or saved information of third parties, or investigate circumstances pointing to illegal activity.
      Our obligations to remove or block the use of information under generally applicable laws remain unaffected by this as per
      §§ 8 to 10 of the Telemedia Act (TMG).

      <br><br>Accountability for links<br>
      Responsibility for the content of
      external links (to web pages of third parties) lies solely with the operators of the linked pages. No violations were
      evident to us at the time of linking. Should any legal infringement become known to us, we will remove the respective
      link immediately.<br>

  </div>
</div>

app/views/home/index.html.erb
<div class="jumbotron jumbotron-fluid hero hero__index">

</div>

<div class="section">
  <div class="container">
    <div class="row headline">
      <div class="col">
        <h2>IOTΛ 4 Earth Projects</h2>
        <p>IOTΛ 4 Earth is an initiative to highlight projects and people from the IOTΛ community that have a positive impact on the mother nature. All these projects are housed by the IOTΛ Ecosystem and are tagged with "iota4earth".</p>
      </div>
    </div>
    <div class="card-list">
      <% if @projects %>
        <% @projects.each do |project| %>

        <div class="card">
          <div class="card-img-top" style="background-image: url('<%= image_url(project["hero"]) %>')" alt="Card image cap"></div>
          <div class="card-body">
            <h6 class="card-subtitle mb-2 text-muted"><%= project["category"] %></h6>
            <h5 class="card-title"><%= project["name"] %></h5>
            <p class="card-text"><%= project["vision"] %></p>
          </div>
          <div class="card-footer">
            <%= link_to "Visit on Ecosystem", project["eco_url"], class: 'btn btn-green-outline', target: '_blank' %>
            <%#= link_to "Donate", "", class: 'btn btn-green-outline', target: '_blank' %>
          </div>
        </div>

        <% end %>
      <% else %>
        <div class="col">
          <div class="alert alert-warning text-center">
            <strong>No projects here at the moment</strong> - add "iota4earth" as an tag to your published <a href="https://ecosystem.iota.org" target="_blank">IOTA Ecosystem</a> project!
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/mission.html.erb
<div class="jumbotron jumbotron-fluid hero">
  <div class="container">
    <div class="row">
      <div class="col">

      </div>
      <div class="col">
        <h1>IOTΛ 4 Earth Mission</h1>
        <p class="lead">To start a movement through which activities aimed at environmental protection are shared among each other through online platforms and given micro rewards in IOTA cryptocurrency by a community of activists spread globally.</p>
        <a href="https://medium.com/iota4earth/the-iota-for-earth-initiative-iota4earth-770a1d82ff10" target="_blank">
          <span>Read more about it on medium.</span>
        </a>
      </div>
    </div>
  </div>
</div>

<div class="section">
  <div class="container">
    <div class="row">
      <div class="col">
        <h2>Key Goals</h2>
        <ul>
          <li>Building up a community of activists for the project</li>
          <li>Creation of awareness via social media platforms and other online forums</li>
          <li>Popularizing #iota4earth hashtag on online platforms</li>
          <li>Providing basic education on how to use IOTA cryptocurrency for micro rewarding to the community of environmental activists</li>
          <li>Building essential software integrations like an IOTA Tip bot which will make micro rewarding hassle free</li>
          <li>Arranging meetups, seminars and other activities</li>
          <li>Liaison with the various organisations in the world which are currently working on environmental issues</li>
        </ul>
      </div>
      <div class="col col__img">
        <%= image_tag("target.svg") %>
      </div>
    </div>
  </div>
</div>

<!-- https://www.youtube.com/watch?v=6EA-MIYY1bg&list=RDhi4pzKvuEQM&index=15 -->

app/views/home/people.html.erb
<div class="jumbotron jumbotron-fluid hero hero__people">

</div>

<div class="section">
  <div class="container">
    <div class="row headline">
      <div class="col">
        <h2>IOTΛ 4 Earth People</h2>
        <p>People make it happen! Join the initiative by adding "iota4earth" as interest tag in the IOTA Ecosystem.</p>
      </div>
    </div>
    <div class="card-list">
      <% if @people %>

        <% @people.each do |user| %>

        <div class="card">
          <div class="avatar rounded-circle" style="background-image: url('<%= user["avatar"] %>')"></div>
          <div class="card-body">
            <h6 class="card-subtitle mb-2 text-muted"><%= user["category"] %></h6>
            <h5 class="card-title"><%= user["name"] %></h5>
            <p class="card-text"><%= user["vision"] %></p>
          </div>
          <div class="card-footer">
            <%= link_to "Visit on Ecosystem", user["eco_url"], class: 'btn btn-green-outline', target: '_blank' %>
            <%#= link_to "Donate", "", class: 'btn btn-green-outline', target: '_blank' %>
          </div>
        </div>

        <% end %>

      <% else %>
        <div class="col">
          <div class="alert alert-warning text-center">
            <strong>No people here at the moment</strong> - add "iota4earth" as an interest to your <a href="https://ecosystem.iota.org" target="_blank">IOTA Ecosystem</a> user profile!
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>



<!-- https://www.youtube.com/watch?v=6EA-MIYY1bg&list=RDhi4pzKvuEQM&index=15 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Iota4earth</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render 'application/favicon' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,700" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg fixed-top">
      <a class="navbar-brand" href="/">
        <%= image_tag("logo.svg") %>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <div class="navbar-toggler-wrapper">
          <span class="line line__top"></span>
          <span class="line line__center"></span>
          <span class="line line__bottom"></span>
        </div>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item <%= "active" if request.path == '/' %>">
            <a class="nav-link" href="/">Home<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item <%= "active" if request.path == '/mission' %>">
            <a class="nav-link" href="/mission">Mission</a>
          </li>
          <li class="nav-item <%= "active" if request.path == '/people' %>">
            <a class="nav-link" href="/people">People</a>
          </li>
        </ul>
      </div>
    </nav>
    <main>
      <%= yield %>
    </main>

    <footer class="page-footer font-small blue">

      <!-- Copyright -->
      <div class="footer-copyright text-center py-3">
        <%= link_to "Imprint", imprint_path  %>
      </div>
      <!-- Copyright -->

    </footer>
  </body>
</html>